<a href="https://colab.research.google.com/github/MariyaYu/Lesson_1/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv("food.csv")

In [6]:
data

,Category,Description,Nutrient Data Bank Number,Data.Alpha Carotene,Data.Beta Carotene,Data.Beta Cryptoxanthin,Data.Carbohydrate,Data.Cholesterol,Data.Choline,Data.Fiber,...,Data.Major Minerals.Phosphorus,Data.Major Minerals.Potassium,Data.Major Minerals.Sodium,Data.Major Minerals.Zinc,Data.Vitamins.Vitamin A - RAE,Data.Vitamins.Vitamin B12,Data.Vitamins.Vitamin B6,Data.Vitamins.Vitamin C,Data.Vitamins.Vitamin E,Data.Vitamins.Vitamin K
0,Milk,"Milk, human",11000000,0,7,0,6.89,14,16.0,0.0,...,14,51,17,0.17,61,0.05,0.011,5.0,0.08,0.3
1,Milk,"Milk, NFS",11100000,0,4,0,4.87,8,17.9,0.0,...,103,157,39,0.42,59,0.56,0.060,0.1,0.03,0.2
2,Milk,"Milk, whole",11111000,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
3,Milk,"Milk, low sodium, whole",11111100,0,7,0,4.46,14,16.0,0.0,...,86,253,3,0.38,29,0.36,0.034,0.9,0.08,0.3
4,Milk,"Milk, calcium fortified, whole",11111150,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7078,Tomatoes as ingredient in omelet,Tomatoes as ingredient in omelet,99997802,103,464,0,5.48,0,7.4,1.6,...,30,278,6,0.21,43,0.00,0.104,18.2,0.60,8.8
7079,Other vegetables as ingredient in omelet,Other vegetables as ingredient in omelet,99997804,1,11,0,4.81,0,19.4,1.4,...,96,364,6,0.58,1,0.04,0.123,6.3,0.03,0.4
7080,Vegetables as ingredient in curry,Vegetables as ingredient in curry,99997810,368,994,0,11.60,0,14.6,2.2,...,46,312,19,0.28,98,0.00,0.177,16.2,0.24,8.9
7081,Sauce as ingredient in hamburgers,Sauce as ingredient in hamburgers,99998130,0,194,4,17.14,13,20.0,0.6,...,33,190,845,0.21,21,0.04,0.104,2.5,1.90,50.8
7082,Industrial oil as ingredient in food,Industrial oil as ingredient in food,99998210,0,0,0,0.00,0,0.2,0.0,...,0,0,0,0.01,0,0.00,0.000,0.0,10.50,155.8

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7083 entries, 0 to 7082
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Category                        7083 non-null   object
 1   Description                     7083 non-null   object
 2   Nutrient Data Bank Number       7083 non-null   int64
 3   Data.Alpha Carotene             7083 non-null   int64
 4   Data.Beta Carotene              7083 non-null   int64
 5   Data.Beta Cryptoxanthin         7083 non-null   int64
 6   Data.Carbohydrate               7083 non-null   float64
 7   Data.Cholesterol                7083 non-null   int64
 8   Data.Choline                    7083 non-null   float64
 9   Data.Fiber                      7083 non-null   float64
 10  Data.Lutein and Zeaxanthin      7083 non-null   int64
 11  Data.Lycopene                   7083 non-null   int64
 12  Data.Niacin                     7083 non-null   float64
 13  Data.Protein                    7083 non-null   float64
 14  Data.Retinol                    7083 non-null   int64
 15  Data.Riboflavin                 7083 non-null   float64
 16  Data.Selenium                   7083 non-null   float64
 17  Data.Sugar Total                7083 non-null   float64
 18  Data.Thiamin                    7083 non-null   float64
 19  Data.Water                      7083 non-null   float64
 20  Data.Fat.Monosaturated Fat      7083 non-null   float64
 21  Data.Fat.Polysaturated Fat      7083 non-null   float64
 22  Data.Fat.Saturated Fat          7083 non-null   float64
 23  Data.Fat.Total Lipid            7083 non-null   float64
 24  Data.Major Minerals.Calcium     7083 non-null   int64
 25  Data.Major Minerals.Copper      7083 non-null   float64
 26  Data.Major Minerals.Iron        7083 non-null   float64
 27  Data.Major Minerals.Magnesium   7083 non-null   int64
 28  Data.Major Minerals.Phosphorus  7083 non-null   int64
 29  Data.Major Minerals.Potassium   7083 non-null   int64
 30  Data.Major Minerals.Sodium      7083 non-null   int64
 31  Data.Major Minerals.Zinc        7083 non-null   float64
 32  Data.Vitamins.Vitamin A - RAE   7083 non-null   int64
 33  Data.Vitamins.Vitamin B12       7083 non-null   float64
 34  Data.Vitamins.Vitamin B6        7083 non-null   float64
 35  Data.Vitamins.Vitamin C         7083 non-null   float64
 36  Data.Vitamins.Vitamin E         7083 non-null   float64
 37  Data.Vitamins.Vitamin K         7083 non-null   float64
dtypes: float64(22), int64(14), object(2)
memory usage: 2.1+ MB

Из полученных данных видим, что незапоненные ячейки отсутствуют. А также видим тип данных по каждой позиции.

In [8]:
data.describe()

,Nutrient Data Bank Number,Data.Alpha Carotene,Data.Beta Carotene,Data.Beta Cryptoxanthin,Data.Carbohydrate,Data.Cholesterol,Data.Choline,Data.Fiber,Data.Lutein and Zeaxanthin,Data.Lycopene,...,Data.Major Minerals.Phosphorus,Data.Major Minerals.Potassium,Data.Major Minerals.Sodium,Data.Major Minerals.Zinc,Data.Vitamins.Vitamin A - RAE,Data.Vitamins.Vitamin B12,Data.Vitamins.Vitamin B6,Data.Vitamins.Vitamin C,Data.Vitamins.Vitamin E,Data.Vitamins.Vitamin K
count,7.083000e+03,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000,...,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000,7083.000000
mean,4.884965e+07,43.759283,255.363405,4.862346,20.828039,34.458845,34.440802,1.703840,213.351687,263.571933,...,133.088945,217.127488,340.503459,1.281451,73.139065,0.705177,0.197528,5.696216,1.086955,14.206607
std,2.425159e+07,259.520139,995.709951,38.047657,21.887363,77.479105,43.901497,2.558168,1015.888615,1161.245139,...,126.498700,204.812523,350.333632,2.917233,241.913126,2.502821,0.374608,15.548490,3.133890,54.944096
min,1.100000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.715077e+07,0.000000,0.000000,0.000000,5.650000,0.000000,10.000000,0.100000,0.000000,0.000000,...,48.000000,111.000000,124.000000,0.360000,2.000000,0.000000,0.052000,0.000000,0.230000,0.800000
50%,5.326020e+07,0.000000,8.000000,0.000000,13.300000,8.000000,19.600000,1.000000,18.000000,0.000000,...,102.000000,183.000000,313.000000,0.680000,20.000000,0.180000,0.110000,0.700000,0.550000,3.800000
75%,6.720345e+07,1.000000,73.000000,1.000000,26.195000,46.000000,44.200000,2.100000,81.000000,0.000000,...,189.000000,270.500000,454.000000,1.360000,61.000000,0.550000,0.203000,5.300000,1.110000,9.300000
max,9.999821e+07,4655.000000,14134.000000,1922.000000,100.000000,3074.000000,820.200000,46.200000,15643.000000,45902.000000,...,1429.000000,6040.000000,7851.000000,98.860000,9363.000000,82.440000,12.000000,560.000000,149.400000,1640.000000